name: 0.0.2 test

on:
  push:
    branches: [ "0.0.2" ]
  pull_request:
    branches: [ "0.0.2" ]
  workflow_dispatch:

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Remove GitHub workflows directory
      - name: Remove .github/workflows
        run: |
          rm -rf .github/workflows

      # Create internal module zip
      - name: Create internal module zip
        run: |
          zip -r galaxy-a03-new-features-test.zip . \
            -x ".git/*" ".github/*"

      # Create outer flashable zip containing only the internal zip
      - name: Create flashable zip
        run: |
          mkdir flash
          mv galaxy-a03-new-features-test.zip flash/
          cd flash
          zip -r ../flash-module.zip galaxy-a03-new-features-test.zip

      # Upload final flashable package
      - name: Upload flashable artifact
        uses: actions/upload-artifact@v4
        with:
          name: flash-module
          path: flash-module.zip
