name: 0.0.2 test

on:
  push:
    branches: [ "0.0.2" ]
  pull_request:
    branches: [ "0.0.2" ]
  workflow_dispatch:

jobs:
  zip_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Prepare module directory
      - name: Prepare internal module directory
        run: |
          mkdir module-dir
          cp -r ./* module-dir/

      # Create internal module zip
      - name: Create internal module zip
        run: |
          cd module-dir
          zip -r galaxy-a03-new-features-test.zip ./*
          mv galaxy-a03-new-features-test.zip ../

      # Prepare flashable directory
      - name: Prepare flashable directory
        run: |
          mkdir flash-dir
          mv galaxy-a03-new-features-test.zip flash-dir/

      # Create outer flashable zip
      - name: Create outer flashable zip
        run: |
          cd flash-dir
          zip -r ../flash-module.zip galaxy-a03-new-features-test.zip

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flash-module
          path: flash-module.zip
